---
version: '3.7'

services:
  web:
    container_name: pittari_web
    hostname: pittari_web
    image: pittari
    build:
      context: ./
    restart: always
    expose:
      - '8080'
    networks:
      - planet-link
    logging:
      driver: "json-file"
      options:
        max-file: '4'
        max-size: '250m'
networks:
  planet-link:
    external:
      name: planet-link
