---
version: '3.6'

services:
  web:
    image: pittari
    hostname: pittari_web
    build:
      context: ./
    container_name: pittari_web
    restart: always
    networks:
      - planet-link
networks:
  planet-link:
    external:
      name: planet-link
