name: Build on Linux

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - magistra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '> 1.15.0'
      - name: Build
        run: |
          export GO111MODULE="on"
          make build
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: Pittari_linux_x86_64
          path: .bin/Pittari
