name: Build on macOS

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - magistra

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '> 1.15.0'
      - name: Build
        run: make build
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: Pittari_macOS_x86_64
          path: .bin/Pittari

